version: '3'
services:
  distributed_dijkstra1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000 

  distributed_dijkstra2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
    depends_on:
      - distributed_dijkstra1
      - distributed_dijkstra2